### ISSUE TITLE
Program will not even consider to open.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Omega1105/gnomeextractor#2]
```
What steps will reproduce the problem?
1. Downloading the installer for 4.1.1
2. Installing 4.1.1
3. Running 4.1.1

What is the expected output? What do you see instead?
Expected: The program to open.
Get: "
EventType : clr20r3     P1 : gnomeextractor.exe     P2 : 0.4.4771.40374     
P3 : 51002b2d     P4 : gnomeextractor     P5 : 0.4.4771.40374     P6 : 51002b2d
P7 : 18b     P8 : 4e     P9 : system.io.filenotfoundexception  
"
Please attach your output.log, stored at %AppData%\Gnome Extractor. If this
file is not present, provide your program and OS version.
Program Version: 4.1.1
OS Version: Microsoft Windows XP
Professional
Version 2002
Service Pack 3
```

Original issue reported on code.google.com by `Blase.Zi...@gmail.com` on 17 Jun 2013 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
Thought I was having the same problem with the program crashing on open, 
returning a filenotfoundexception error. 

Reinstalled, and noticed that when I selected steamapps\common\gnomoria, the 
installer actually used steamapps\common\gnomoria\gnomoria. I manually deleted 
the second \gnomoria entry and installed again, worked perfectly. 

Hope that saves some time.
```

Original comment by `swartz.j...@gmail.com` on 18 Jun 2013 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I tried that and got this
=== Start of logging 2013-06-25 12:31:58.5939 ===
*** 2013-06-25 12:31:58.4279 DEBUG  ->Gnomoria version found: 0.8.42.0
*** 2013-06-25 12:31:58.6319 DEBUG  ->Gnome Extractor version: 0.4.1.1
*** 2013-06-25 12:31:58.6319 DEBUG  ->OS found: Microsoft Windows NT 6.1.7601 
Service Pack 1
*** 2013-06-25 12:31:58.6439 DEBUG  ->OS found: 64 bit
*** 2013-06-25 12:31:58.6519 DEBUG  ->.Net version found: 4.0.30319.296
*** 2013-06-25 12:32:00.0880 INFO   ->Gnome Extractor is running...
*** 2013-06-25 12:32:02.2161 FATAL  ->System.Windows.Markup.XamlParseException: 
'The invocation of the constructor on type 'GnomeExtractor.MainWindow' that 
matches the specified binding constraints threw an exception.' Line number '5' 
and line position '9'. ---> System.BadImageFormatException: Could not load file 
or assembly '0 bytes loaded from System, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b77a5c561934e089' or one of its dependencies. An attempt was 
made to load a program with an incorrect format. ---> 
System.BadImageFormatException: Bad IL format.
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence securityEvidence)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at GnomeExtractor.Settings.ReadXml()
   at GnomeExtractor.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at GnomeExtractor.App.Main()

```

Original comment by `rushedma...@gmail.com` on 25 Jun 2013 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
Same
```

Original comment by `fabiende...@gmail.com` on 19 Jul 2013 at 9:45
